Add conversion from FAO to IPCC2006_PRIMAP
primap-community/FAOSTAT_data_primap pull request #6
Opened 2024-12-03 14:22 UTC by crdanielbusch

## Description

- write a test that performs the conversion
- add the FAO categorisation
- add the conversion

## Checklist

Please confirm that this pull request has done the following:

- [ ] Tests added
- [ ] Documentation added (where applicable)
- [ ] Changelog item added to `changelog/`

2025-03-06 09:01 UTC, JGuetschow requested changes
Hi, I've modified the sector mapping and aggregation quite a bit so make sure we have a consistent hierarchy on the IPCC side and map all things that are not included into m categories. I hope it all works. I did not expect it to be so much, else I would not have done it with the github comments

2025-03-17 08:14 UTC, JGuetschow approved these changes
Approve unless answers to my comments require changes,

2025-03-17 08:14 UTC, JGuetschow commented on src/faostat_data_primap/helper/country_mapping.py
> +    "Ascension, Saint Helena and Tristan da Cunha": "SHN",
Are both of these used?

2025-03-17 08:14 UTC, JGuetschow commented on src/faostat_data_primap/helper/definitions.py
> +                "All Crops - Crop residues (Direct emissions N2O)",
Why do you remove these. Don't they map to `3.C.4` (direct) and `3.C.5` (indirect), so it would make sense to keep direct and indirect emissions? Or are they redundant or empty?

2025-03-17 08:14 UTC, JGuetschow commented on src/faostat_data_primap/read.py
> +        df_all["Source"] = "FAO TIER 1"
Is all FAO data Tier 1?

2025-03-17 08:36 UTC, crdanielbusch commented on src/faostat_data_primap/helper/country_mapping.py
> +    "Ascension, Saint Helena and Tristan da Cunha": "SHN",
Yes, we need both

2025-03-17 08:39 UTC, crdanielbusch commented on src/faostat_data_primap/helper/definitions.py
> +                "All Crops - Crop residues (Direct emissions N2O)",
Treu, that would be a better option. We could do:

"All Crops - Crop residues (Direct emissions N2O)" -> FAO M.1.CR.direct -> IPCC 3.C.4 Direct N2O Emissions from Managed Soils

and 

"All Crops - Crop residues (Indirect emissions N2O)" -> FAO M.1.CR.indirect -> IPCC 3.C.5 Indirect N2O Emissions from Managed Soils

2025-03-17 08:42 UTC, crdanielbusch commented on src/faostat_data_primap/read.py
> +        df_all["Source"] = "FAO TIER 1"
I guess so. The CSVs sometimes lack the "Source" column, but the FAOSTAT data explorer always shows "FAO Tier 1"

2025-03-17 09:42 UTC, crdanielbusch commented on src/faostat_data_primap/helper/definitions.py
> +                "All Crops - Crop residues (Direct emissions N2O)",
I updated the categories. Since I am at it, I can also split M.3.C.45.MP (manure on pasture), M.3.C.45.MA (manure applied to soils) by direct and indirect N2O emissions. But I'm wondering which values are more accurate. In this example, "M.1.CR.direct" and "M.1.CR.indirect" does not add up to "M.1.CR". Similarly to the other categories we see rounding errors of up to 100%. Wouldn't the parent category be the more accurate choice then?

2025-03-18 08:23 UTC, JGuetschow commented on src/faostat_data_primap/helper/definitions.py
> +                "All Crops - Crop residues (Direct emissions N2O)",
hmm, it's annoying if we have rounding errors. But on the other hand we can't map to proper IPCC categories without the distinction between direct and indirect. How many countries are affected by the rounding errors?

2025-03-18 08:33 UTC, crdanielbusch commented on src/faostat_data_primap/helper/definitions.py
> +                "All Crops - Crop residues (Direct emissions N2O)",
Roughly 5-15 countries depending on the year. Not necessarily the same countries. Without checking the country codes, I'd say mostly small countries. here's an example year from the error message:

```
E               2014-01-01 ATG          0.019231
E                          BHR          0.028571
E                          BMU          0.083333
E                          COK          0.021739
E                          ESH          0.031250
E                          FLK          0.083333
E                          MAC          0.028571
E                          NIU          0.200000
E                          NRU          0.200000
E                          PYF          0.012195
```

2025-03-26 11:06 UTC, merged